cluster_name      = "wavelength"
wavelength_zone   = "us-east-1-wl1-dfw-wlz-1"
wavelength_zone_2 = "us-east-1-wl1-bos-wlz-1"
worker_key_name   = "test_key"
domain            = "aceg1357.com"
zoneid            = "testzone"
